# Generated by Django 4.0.5 on 2022-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rejisor', models.CharField(max_length=100)),
                ('type_film', models.CharField(max_length=50)),
                ('about_film', models.CharField(max_length=500)),
            ],
        ),
    ]
