# Generated by Django 4.0.5 on 2022-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='pochta',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
